name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-docker-login@v1
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          username: ${{ secrets.DOCKERIO_USERNAME }}
          password: ${{ secrets.DOCKERIO_PASSWORD }}
      -
        uses: docker/setup-buildx-action@master
        # with:
        #   driver-opt:
        #     - image=moby/buildkit:master
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Validate all
        run: |
          ./hack/ci
      -
        name: Publish master
        if: ${{ success() && github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: |
          NAME_SUFFIX=master docker buildx bake --push --progress=plain mainline-all buildkit-helper-all
